sudo: false
language: python
python: 3.3

env:
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35

install:
  - pip install tox coverage

script:
    - tox -e $TOXENV

matrix:
    include:
        - python: 3.5
          env: TOXENV=py35
